apiVersion: v1
kind: Service
metadata:
  name: result-service
  namespace: {{ .Values.namespace }}
  labels:
    name: result-service
    app: demo-voting-app
spec:
  type: NodePort
  ports:
   - port: 80
     targetPort: 80
     nodePort: 30005
  selector:
    label-name: result-pod
    app: demo-voting-app
