apiVersion: v1
kind: Service
metadata:
  name: voting-service
  namespace: {{ .Values.namespace }}
  labels:
    name: voting-service
    app: demo-voting-app
spec:
  type: NodePort
  ports:
   - port: 80
     targetPort: 80
     nodePort: 30001
  selector:
    label-name: voting-pod
    app: demo-voting-app
