apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: result-app-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/wave: "1"
#    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: {{ .Values.ingressClassName }}
  rules:
  - host: hpresult.120v.ac
    http:
      paths:
      - path: /  
        pathType: Prefix
        backend:
          service:
            name: result-service
            port:
              number: 80
