apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: {{ .Values.namespace}}
  annotations:
    argocd.argoproj.io/wave: "-1"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Minimal storage size
  storageClassName: local-storage  # Should match the StorageClass defined for the PV
