kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-volume
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/wave: "-1"     
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 1Gi
  accessModes:
   - ReadWriteOnce
  hostPath:
    path: /home/ubuntu/postgres_data
