apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/wave: "-1"  
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=  
  POSTGRES_PASSWORD: cG9zdGNyZXM=  
