apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/wave: "-2"
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
